### ISSUE TITLE
Export M3U Playlist from Xtream Connection

### ISSUE THREAD

**Issue by wilsoniain** [PhunkyBob/iptv_playlist_browser#1]
Could an M3U playlist be exported from an xtream connection easily?

**Comment by 3v3rm4rt3lL** [comment]
@PhunkyBob  I couldnt make work. Is there additional things to do? Thanks.

**Comment by PhunkyBob** [comment]
What is your problem exactly?

**Comment by 3v3rm4rt3lL** [comment]
I really do not at all about program code or how use , I download this
project and always opens the gui interface but I couldnt see any " export
m3u configuration" inside.

**Comment by PhunkyBob** [comment]
I haven't added "export m3u configuration" in my version.

To download your M3U, just replace `server`, `username` and `password` in the following URL. 
```
{server}/get.php?username={username}&password={password}&type=m3u_plus
```
I'll try to add this feature in a next release.

**Comment by 3v3rm4rt3lL** [comment]
May I trying to do something wrong, I would like to get a m3u list from xtream codes api, because my provider block get.php?, so this could be done with your project? ( talking about this  " dummy code for xtream codess ). Thanks.

**Comment by PhunkyBob** [comment]
I expected to add this feature using the `get.php` feature. 
If it doesn't work, I'll need to write something from the data I retreive from the provider.

**Comment by 3v3rm4rt3lL** [comment]
Oh, great. I'll be watching this. Thank you. Great project.

**Comment by PhunkyBob** [comment]
I've published a new version with "download playlist" and "generate playlist" feature.

Tell me if it's OK for you.

**Comment by 3v3rm4rt3lL** [comment]
"Generate playlist" is just that I need, this is awesome. Thank so much.   The best wishes to you.
