### ISSUE TITLE
Release exe is detected as Trojan by Windows Defender

### ISSUE THREAD

**Issue by tanujmalkani** [PhunkyBob/iptv_playlist_browser#6]
![Screenshot 2023-09-02 182608](https://github.com/PhunkyBob/iptv_playlist_browser/assets/57258702/8c0de6ca-ef9f-46e8-b477-429fcfb12677)

**Comment by PhunkyBob** [comment]
False positive, like any program compiled with Nuitka.
Don't hesitate to use Python interpreter, it will be more secure.
