### ISSUE TITLE
merge my script with xtream api ?

### ISSUE THREAD

**Issue by bellad17** [PhunkyBob/iptv_playlist_browser#7]
Hello,
 thank you for your app , now i can export m3u with xtream code
after i put m3u file with my script for write new m3u file filtre for my need 
 it's possible merge my script with yours for automate ?
I ask you because you are stronger than me in python , mr I'm just starting out
thank
my code
`f=open('tv.m3u','r')
nb=0
for line in f:
	nb+=1
f.close()
f=open('tv.m3u','r')
c=open('IPTVfr.m3u','a')
c.write('#EXTM3U'+'\n')
lines = map(lambda ch: ch.strip('\n'), f.readlines())	
ch="FRANCE TNT"
ci="FRANCE MY CANAL"
cj="FRANCE DIVERTISSEMENT"
ck="FRANCE MUSIQUE"
cl="FRANCE CINEMA"
for i in range(nb):
	if ci in lines[i] or ch in lines[i] or cj in lines[i] or ck in lines[i] or cl in lines[i]:
		c.write(lines[i]+'\n')
		c.write(lines[i+1]+'\n')
f.close()
c.close()
`

**Comment by izneo-get** [comment]
Que souhaitez-vous faire précisément ?

**Comment by PhunkyBob** [comment]
Que souhaitez-vous faire exactement ?

**Comment by bellad17** [comment]
l'idéale serai  : mettre les infos de xtream (identifiant , password , lien)  > enregistre le fichier m3u > lit ce fichier avec mon code pour filtrer le "FR"
en un seul script python sous debian
pour le moment je lance  iptv_playlist_browser sous windows pour recuperer le m3u , puis je lance mon script sous debian pour le filtrer , que je mets ensuite sur emby server
merci beaucoup

**Comment by PhunkyBob** [comment]
Pourquoi n'utilisez-vous pas `iptv_playlist_browser` directement sous Debian ?
Je ne souhaite pas intégrer un script qui filtre automatiquement sur les "FR" car ce n'est pas une fonctionnalité qui intéresse la grande majorité des utilisateurs, et ce n'est pas forcément "FR" qui indique les flux français. 
Je vais réfléchir à comment intégrer un filtre plus générique. 

Malheureusement, je n'ai plus accès actuellement à un compte Xstream. Il faut que j'en retrouve un pour faire mes tests.

**Comment by bellad17** [comment]
c'est vrai que ça diffère en fonction du fournisseur
je peux te donner le mien qui se termine le 24 de ce mois , comment en le faire en cacher !!

**Comment by PhunkyBob** [comment]
Tu peux le mettre dans un Pastebin avec "burn after read". https://pastebin.com/
Ensuite, mettre en commentaire le lien ici et 10 secondes après supprimer le message. 
Je devrais recevoir une notif email avec les premières lignes du message.

**Comment by bellad17** [comment]
confirme moi si tu l'a recu

**Comment by PhunkyBob** [comment]
Reçu 👍

**Comment by PhunkyBob** [comment]
Dans la version 1.06.0 (ce31b53a17f675ffe5bc59e631d97e61cebd0a14), la fenêtre d'export de la playlist permet de filtrer sur les noms de groupe et les noms de chaines / films.
Il est possible de mettre plusieurs valeurs séparées par une virgule.

Par exemple en mettant dans le filtre de groupe `FRANCE,ARABIC` et dans le filtre de titre `BEIN`, la playlist générée ne contiendra que les chaines qui contiennent le mot "BEIN" et qui sont dans un groupe qui contient au moins le mot "FRANCE" ou le mot "ARABIC". 

Peux-tu me dire si ça répond à ton besoin ?

**Comment by bellad17** [comment]
ok , je vais essayer , comment je fais en ligne de commande , car sur debian il n'y a que console , pas de desktop
merci

**Comment by PhunkyBob** [comment]
Effectivement, sur un serveur sans possibilité d'afficher les applications, il n'est pas possible de lancer `iptv_playlist_browser`...
Mais de toutes façons il n'est pas non plus possible d'exécuter VLC !

**Comment by bellad17** [comment]
ça tombe bien je ne veux pas executer vlc , donc je reviens avec windows pour iptv_playlist_browser , peux tu me le compiler avec la version 1.06 pour windows , que je test ?
merci

**Comment by PhunkyBob** [comment]
Je galère depuis hier soir pour faire l'exécutable. Je ne sais pas pourquoi, la fonction qui permet d'ouvrir les boites de dialogue ne fonctionne pas.
Je continue mes tentatives...

En attendant, il tourne très bien avec Python sous Windows.

**Comment by PhunkyBob** [comment]
Tu peux essayer cet exécutable : https://gofile.io/d/cpGdpB
Les fenêtres "ouvrir un fichier" ou "sélectionner un répertoire" ne fonctionnent pas, mais si tu remplis les chemins à la main, ça semble fonctionner.

**Comment by bellad17** [comment]
ok , merci ça marche , effectivement il faut le mettre à la main , la souris non plus ne peut pas selectionner "live" , je le fait avec tab et espace pour cocher

**Comment by PhunkyBob** [comment]
C'est bon, j'ai pu créer l'exécutable en changeant le style des fenêtres de choix de fichier / répertoires.
b8868a0
